### ISSUE TITLE
Units of step

### ISSUE THREAD

**Issue by jr23mx** [trimesh/cascadio#11]
how can I know the units of the step imported?

**Comment by mikedh** [comment]
Hey, the implicit default units for GLB are meters, so everything should be in meters unless there's a bug somewhere.

**Comment by spaulsteinberg** [comment]
Hi @mikedh , thanks again for this amazing library. Is there any way we can specify the units for step_to_glb ? 

For example, I have models in millimeters that are being essentially scaled down because like you mentioned, meters are expected.
