### ISSUE TITLE
出现报错，关于如何运行启动项目，有没有办法解决？

### ISSUE THREAD

**Issue by gino330012** [trimesh/cascadio#13]
-- Configuring incomplete, errors occurred!
PS C:\Users\cosmo\PycharmProjects\cascadio-kl\upstream\OCCT> cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="C:/MinGW/bin/gcc.exe" -DCMAKE_CXX_COMPILER="C:/MinGW/bin/g++.exe" -DCMAKE_MAKE_PROGRAM="C:/utils/ninja/ninja-win/ninja.exe" -DFREETYPE_INCLUDE_DIRS="C:/utils/ft/ft2133/freetype-2.13.3/include" -DUSE_RAPIDJSON:BOOL="ON" -D3RDPARTY_RAPIDJSON_INCLUDE_DIR="../rapidjson/include" .   
-- Info: TCL is used by OCCT
-- Info: TK is used by OCCT
-- Info: FreeType is used by OCCT
-- Could NOT find Freetype (missing: FREETYPE_LIBRARY) 
-- Info: TKIVtk and TKIVtkDraw toolkits excluded due to VTK usage is disabled
CMake Error at CMakeLists.txt:868 (message):
  Could not find headers of used third-party products:
  3RDPARTY_FREETYPE_INCLUDE_DIR_ft2build
  3RDPARTY_FREETYPE_INCLUDE_DIR_freetype2

-- Configuring incomplete, errors occurred!

**Comment by mikedh** [comment]
Hey, I'd recommend using the wheels, if you want to build it yourself you probably need to use `cibuildwheel` or run the commands in the `before-all` yourself (note the `-DUSE_FREETYPE:BOOL="OFF"`):
https://github.com/trimesh/cascadio/blob/67148611182877e361daef137276849947aed53d/pyproject.toml#L45-L52
