### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by musicinmybrain** [trimesh/cascadio#5]
To help distribution packagers and others who need to rebuild the wheels from source, please push tags corresponding to the PyPI releases – especially since no sdists are released on PyPI. Thanks!

**Comment by mikedh** [comment]
Should be fixed. Especially important as this already hit the 10gb size limit on PyPi and I had to delete a bunch of old releases. I'll have to add a note for people version pinning to stick to latest or a specifically chosen release.
